a=8 #num1
b=6#num2
c=2 #num3
s=a+b+c #sum
print(s)
d=a-b-c #difference
print(d)
avg=s/3 #average
print (a)
p=a*b*c #product
print(p)
B=10 #base in cm 
H=20 #height in cm 
A=1/2*B*H #Area of triangle in cm^2
print(A)
s1=9 #side of square in cm
S=s1*s1 #area of squre in cm^2
print(s)
r=12 #radius of circle in cm
c=22/7*r**2 # area of cicle in cm^2
print(c)
l=5 #length of a rectangle in cm
w=13 # width of a rectangle in cm
R=l*w #area of rectangle cm^2
print(R) 


